# Generated by Django 3.2.5 on 2021-08-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210829_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
