# Generated by Django 3.2.5 on 2021-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_articles_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
