# Generated by Django 3.2.5 on 2024-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_series_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('large_url', models.CharField(max_length=200)),
                ('medium_url', models.CharField(max_length=200)),
                ('small_url', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
