# Generated by Django 3.2.5 on 2024-02-25 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_weddingphotos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weddingphotos',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='weddingphotos',
            name='establish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
