# Generated by Django 3.2.5 on 2024-02-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_weddingphotos_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingphotos',
            name='origin_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
