# Generated by Django 3.2.5 on 2024-02-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_weddingphotos_origin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingphotos',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
